### ISSUE TITLE
Explaining object to Stata users

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-r-training#17]
We started to talk about this already in the session, but I think it really helped to explain to Stata users what object are that I think it should go into the slide. 

> An object is like a global in Stata, but while you can only put a number or a string in a global, you can put anything into an object, strings, data sets, vectors, graphs. In Stata you can reference the global later in your code to get it's content, but with an object you can do so much more. Exactly what you can do with an object depends on what you saved in the object, not that it is an object.

Something like that.

**Comment by LeonardoViotti** [comment]
Added to the presentation!
