### ISSUE TITLE
R training - 2018 Nov 20

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-r-training#18]
@ramarty, let's write any ideas, comments etc. that we might think of during the session in this issue thread. Anyone can add to this issue

**Comment by kbjarkefur** [comment]
Slide where we list several packages:
* before people have a better grasp of R and packages in general, I think it is too technical to go over what all the packages does. Maybe move to end of session. Or move to end of course. Or just introduce each package as you need them. I think this fly over the heads of the attendees

**Comment by kbjarkefur** [comment]
in exercise 3 (stargazers and labels)
* make it clear that they should go back to the code they just run with stargazer and modify it so that it takes the labels as an arguemnt

**Comment by kbjarkefur** [comment]
slide with example for `aggregate()`:
* the first slide has outdated syntax

**Comment by kbjarkefur** [comment]
General comment. Do not mention *tidyverse* until you have introduced that properly. It is just confusing to people new to R

**Comment by luizaandrade** [comment]
Changes were made in 9a00314be8c839056a30421ddaa5d6716a169160 and 6d5dbb7aaf86a8987f06322f4016b9ac2c65b9fa (and then I linked to the wrong issue.. duhr!)

**Comment by LeonardoViotti** [comment]
Resolved in 7a60597cdfe243834606c7f0b2a21d18225cfcdc
