### ISSUE TITLE
Lab 3 - April 23

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#28]
- [x] Ask in the beginning of the session if people use LaTeX or Excel
- [x] Explain how R treats missing observations
- [x] Exercise 4: 
 - Mention out argument
- Replace RawOutput by "your/file/path/here"
- [x] Exercise 5 : 
 - Fix stata code
- [x] Exercise 9 : Typo
- [x] Add a Thank you slide

**Comment by LeonardoViotti** [comment]
- [ ] Exercise 4: 
 - Mention out argument

**Comment by luizaandrade** [comment]
@LeonardoViotti, I have added a point on slide 4 saying we'll export tables to LaTeX and excel. This is the cue to ask how many people use either of the software. From there, we can decide which sections of the session to prioritize.

**Comment by luizaandrade** [comment]
Also, I couldn't find a typo in exercise 9
