### ISSUE TITLE
Lab 4 - Apr 25

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#29]
- [x] explain that whr is the data in slide 21
- [x] several typos in slide 21
- [x] Ex 5: show how data looks like and put aggregate and ggplot code in the same slide
- [x] Ex 6: Lots of typos (region not treatment
- [x] ggplot different datasets, move aes() to ggplot function?

**Comment by ramarty** [comment]
maybe before teaching pdf(), dev.off(), teach ggsave() always with height/width? This could just be my preference in using ggsave... I'm wondering if this more common too? (also avoids issue with having a graphics device already open). Or maybe at least include a slide on ggsave?

**Comment by LeonardoViotti** [comment]
- [ ] use labs() function to change the legend titles

**Comment by luizaandrade** [comment]
The labs() function does not set X and Y labels
