### ISSUE TITLE
Lab 5 -  Apr 30

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#30]
- [x] Alternative way of loading shapefile: readOGR(file.path(finalData, "worldmap.shp"))
- [x] Add raster package to the list of packages
- [x] Make sure the packages we install are the same we load
- [x] geom_point() instead of geom_points()

**Comment by LeonardoViotti** [comment]
- [ ] Make sure to mention this is an advanced session. Maybe mention it in the OLC page or something.
