### ISSUE TITLE
Lab 6 - May 2nd

### ISSUE THREAD

**Issue by LeonardoViotti** [worldbank/dime-r-training#31]

**Comment by LeonardoViotti** [comment]
- [ ] Typo in ID variables slide (17)

**Comment by ramarty** [comment]
in addition to rbind, maybe mention bind_rows from tidyverse too -- which can handle datasets with different columns?

https://stackoverflow.com/questions/42887217/difference-between-rbind-and-bind-rows-in-r

**Comment by ramarty** [comment]
instead of write.dta13, maybe use write_dta from the haven package? I think this is a tidyverse package -- and I think haven treats things like value labels & descriptions nicely
