### ISSUE TITLE
R Training 1 - June 11, 2019

### ISSUE THREAD

**Issue by ramarty** [worldbank/dime-r-training#35]
- [x] Tell people to write code in the script window

**Comment by ramarty** [comment]
Exercise 6 (slide 60): use happy_score, not happy_rank

**Comment by LeonardoViotti** [comment]
- [ ] In lab 2, put unindented and indented code examples side by side

**Comment by luizaandrade** [comment]
@luisesanmartin , these notes are about the labs that you are running on Monday, just wanted to make sure you saw them. If you have already changed this in your presentation, feel free to close the issue.

**Comment by luisesanmartin** [comment]
Thanks! I'll make sure to add them 👍

**Comment by luisesanmartin** [comment]
solved in f01041bf0cc7a56a5c1399f8fdeee72a9c068f44
