### ISSUE TITLE
R training-Data visualization

### ISSUE THREAD

**Issue by MariaArnalCanudo** [worldbank/dime-r-training#42]
- [x] Maybe an additional slide with the types of plots (geom_point, geom_line, geom_density, etc.) and color palettes

- [x] For those who want to go further it might be useful to develop some visualizations beyond the training and get feedback from the instructors

- [x] The exercise looks good, but I'd provide two prepared datasets for visualizations so participants are able to work more in the code rather than in data cleaning. Besides, they could share their plots in GitHub or in a shared folder and have a brief peer-review session for feedback.

**Comment by luizaandrade** [comment]
1. Great point, sure worth adding. In terms of palettes, here are a few that I think would be good to add:
- Viridis package (viridis, plasma, etc)
- wesanderson package (my fave <3)
- RColorBrewer

2. Agreed. I think the latest version of the training (on master branch) has that, but great if you can take a look at the current exercise and see if you suggest any changes.

**Comment by luizaandrade** [comment]
@RRMaximiliano , should we plan to add a "homework" at the end of the session next week? We can take time during office hours to review them.
