### ISSUE TITLE
01-intro-to-R-part-1 review notes

### ISSUE THREAD

**Issue by roshni13khincha** [worldbank/dime-r-training#48]
- [ ] Can the slides be aligned to the middle of the page instead of top? 

- [x] Introduction - Might be better to phrase this part of the sentence _and why it is so much better than Stata._ as _how Stata users can adapt utilize some features which are better in R_

I notice this trend through all the intro slides. Don't think we mean to start a war between R and Stata (there's enough of that already!). If that was the plan all along, it's fine to leave those comments in but I think it might be a better approach to just point out how some of R's functions are better than R and let people decide which they prefer to use. Same for the wording of R vs Python

- [x] Introduction - move _part II_ within brackets

- [x] Introduction - _Certain common tasks are simpler in Stata._ Mention a couple of examples.

- [x] Getting started - Ask participants to clone repository before pointing to file locations

- [x] Explain the interface before importing dataset and then go back to interface to explain where the data framex` shows

- [x] `head(whr2015) `and `head(whr)` use the exact same output image. Something is wrong there. Also, might be good to show both the outputs in the same slide

- [x] Data in R - _Two important concepts to take note_  has 3 points

**Comment by luisesanmartin** [comment]
Thanks, Roshni! this is very useful 🥇
