### ISSUE TITLE
Feedback for session of 23 Nov 2020

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#50]
Sessions: Intro I and Intro II

**Comment by kbjarkefur** [comment]
Slide 8 - I might have missed it, but I think you jumped into talking as if we assume they know Stata, but I did not hear us explaining that we are assuming that they know Stata. I could have missed it, but this I think make sense to stress as that is what makes this training unique

**Comment by RRMaximiliano** [comment]
For the examples using the `print()` function, maybe we should mention by we are using quotation marks "" and differences between single or double quotations marks.

**Comment by luizaandrade** [comment]
remove file paths to github repo

**Comment by RRMaximiliano** [comment]
We should also mention that we are executing the command using the console instead of the Rscript. And the pro and cons of it.

**Comment by luizaandrade** [comment]
On subset:
1. Tell people to do Ex 2 (subset data)
2. Ask someone what they see (the full data)
3. Ask someone else to explain what that's happening (not assigned to an object)
4. Ask someone else how this can be fixed (using the assignment operator)

**Comment by luizaandrade** [comment]
on slide 33, it's not clear that there are two `=` sign

**Comment by RRMaximiliano** [comment]
On the notes regarding =, that's an issue using Fira Code. We should either first explain the equal sign thingy or change the font.

**Comment by luizaandrade** [comment]
on slide 37, stress that this is important as you may loose data by replacing it

**Comment by luizaandrade** [comment]
`<-` shows as an arrow, so we need to clarify that too

**Comment by luizaandrade** [comment]
explain that function arguments need to be enclosed by parenthesis, and the RStudio will help you do that

**Comment by luizaandrade** [comment]
fix types of characters on slide 58 to turn (version change)

**Comment by luizaandrade** [comment]
Exercise 7 is a bit confusing. maybe drop it?

**Comment by luizaandrade** [comment]
exercise 1 in session II adds too many complications at this point. let's remove this

**Comment by RRMaximiliano** [comment]
- Stress that `View()` must be capitalized

**Comment by luizaandrade** [comment]
exercise 4 will not start an empty session, given that we did not change the settings

**Comment by luizaandrade** [comment]
exercise 4 in session II: ask why it is preferable to load data using code and not point-and-clicking

**Comment by luizaandrade** [comment]
slide 45 of session 2: change package from `stagazer` to `tidyverse`

**Comment by RRMaximiliano** [comment]
- Since we are mentioning pipes, we need to include the tidyverse before.

**Comment by luizaandrade** [comment]
Luis E's example of raising hands is great! We should ad that to the slides

**Comment by luizaandrade** [comment]
replace all `T` with `TRUE`

**Comment by luizaandrade** [comment]
Remind people to save the master script with their edits

**Comment by luisesanmartin** [comment]
Most comments solved in  72a036b. The ones that required more work were included in #58 , which will be solved in the next training
