### ISSUE TITLE
Feedback - Session: Data Processing (24th Nov)

### ISSUE THREAD

**Issue by RRMaximiliano** [worldbank/dime-r-training#52]
**Session: Data Processing (Wrangling)**

**Comment by luizaandrade** [comment]
slide 6: "exercises", not exercise

**Comment by luizaandrade** [comment]
The explanation of how pipes can become really long was not clear, we got a few questions. maybe move this note to the slide where we show how to use multple pipes?

**Comment by luizaandrade** [comment]
this is fixed
