### ISSUE TITLE
Session 3 - Data Viz - Review

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#53]
- [x] Slide 5: include the same file paths as in previous sessions, so people can reuse their code
- [x] Is there a particular reason why sometimes we see `ggplot` and sometimes `{ggplot}`?
- [x] Slide 17: you can also indicate the data inside the aesthetics. Explain that both will work, but the this will make a difference when you want to use more than one dataset or more than one mapping. Then add an example.
- [x] Slide 19: this link is super cool! I suggest you open it and scroll a bit.
- [x] Slide 26: This is a great opportunity to show the difference between using colors for numeric and factor variables. I think we should first do it without the factor, then ask how many people made the same graph, than ask what is the problem with the graph (that is, that there's little variation in the color, so it's hard to tell them apart) and show the solution of using factors
- [x] Slide 36: I expect the first thing people will ask is how to remove the legend, so maybe put that on the next slide?
- [x] Can we also add some color palettes? Doesn't need to be an exercise, but just do the same graph with a few different palettes is enough.

**Comment by RRMaximiliano** [comment]
> Is there a particular reason why sometimes we see ggplot and sometimes {ggplot}?

There wasn't a particular reason. Can't remember why I didn't lol.

 > Slide 26: This is a great opportunity to show the difference between using colors for numeric and factor variables. I think we should first do it without the factor, then ask how many people made the same graph, than ask what is the problem with the graph (that is, that there's little variation in the color, so it's hard to tell them apart) and show the solution of using factors.

Added information about the factors, and within the same exercise 3 added the factor information and contrast with numerics.

> Can we also add some color palettes? Doesn't need to be an exercise, but just do the same graph with a few different palettes is enough.

Added some noice packages :)

**Comment by luizaandrade** [comment]
Thanks, Rony! I'm excited for this session!!
