### ISSUE TITLE
Feedback - Descriptive Analysis - Nov 30 2020

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#55]

**Comment by RRMaximiliano** [comment]
* Pacman could create confusion if we haven't installed before.

**Comment by luisesanmartin** [comment]
Add prompt on slide 4 to install `pacman`,  `skimr`, `huxtable`, and `lfe`

**Comment by luisesanmartin** [comment]
slide 19: the summary table for continuous variables seems to be truncated. Maybe we should make it smaller or paste it in the next slide

**Comment by RRMaximiliano** [comment]
* Included the formatted version of the table in slide 32.
