### ISSUE TITLE
Feedback - Data Visualization - Nov 30 2020

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#56]

**Comment by luizaandrade** [comment]
- [ ] typo in slide 7: should read "not tidy"

**Comment by luisesanmartin** [comment]
Slide 7: "It will really dif􀁿cult to create good graphics when your data is **not** tidy"

**Comment by luisesanmartin** [comment]
- [ ] slide 14: delete "raw" from the `Data` bullet

**Comment by luizaandrade** [comment]
resolved in 1a69a49
