### ISSUE TITLE
Intro to R - Feedback April 05 2021

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#65]

**Comment by RRMaximiliano** [comment]
Slides: 

* Add explanation of vectors, lists, etc.

**Comment by luisesanmartin** [comment]
The content is still a bit long. Consider deleting a couple of slides on the introduction (exm: R vs Stata)

**Comment by luisesanmartin** [comment]
Include in this session an explanation of libraries, file paths, and R projects

**Comment by luisesanmartin** [comment]
Cut content on introduction and give a bit more time to solve exercises
