### ISSUE TITLE
Notes from 1st session of NISR training

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-r-training#7]
- [x] when to write code in the console vs the script?
- [x] what happens when you create two different objects with the same name?

**Comment by kbjarkefur** [comment]
- [ ] Help them differentiate between what is good to know about R and what they need to know. 
    - Both in the example of web scraping when they do not need to know web scraping but it is really good to know that R can do web scraping
    - Help them understand which commands they "must know" to do regular things in R, and what is a "good trick". Include a lot of "good tricks" in "must knows", but there is a lot of information and help guide them in what they need to learn 

- [ ] I think there is a bit too much information about R and all of it's capabilities before starting to work with some examples. I think attendees are more receptive to details around R once they got the hands a little bit dirty. The information you have is great and should be included, but I think it might be too difficult to make sense of before you haven't even opened a data fram yet

**Comment by luizaandrade** [comment]
- [ ] how to save a script
- [ ] difference between warnings and errors (this is in Lab2, but maybe we can consider moving to 1)

**Comment by LeonardoViotti** [comment]
- [ ] Make sure there are outputs for all code! there are slides that are not that clear
- [ ] How to save your code
- [ ] Better motivation on objects! "The building blocks of R programing"
- [ ] Syntax? maybe a shorter slide.

**Comment by luizaandrade** [comment]
- [ ] show a single way of indexing data frames by variable name, or show both together and not in different slides
- [ ] remove part about attributes of a data frame

**Comment by kbjarkefur** [comment]
- [ ] for the paste() function. A more maybe more relatable example is to have a data frame with a column called first_name and one called last_name and then do `paste(df$first_name[1], df$last_name[1])` to create full name

**Comment by luizaandrade** [comment]
- [ ] simplify Boolean exercise: don't use function Inception, don't use idexing
