### ISSUE TITLE
 Data Analysis - Feedback April 12 2021

### ISSUE THREAD

**Issue by RRMaximiliano** [worldbank/dime-r-training#70]

**Comment by RRMaximiliano** [comment]
Maybe we can load packages before loading the dataset, Slides 4 and 6.

**Comment by RRMaximiliano** [comment]
So, the problem with the learnr app was that the census dataset was not included in the app that was deployed.

**Comment by RRMaximiliano** [comment]
Add openxlsx, to the required packages.

**Comment by luisesanmartin** [comment]
slide 33/60 still has a path defined with `file.path()` instead of `here()`

**Comment by RRMaximiliano** [comment]
Someone mentioned centering columns~~

**Comment by luizaandrade** [comment]
Fix extra quotation marks once we use "%9.0f"

**Comment by luizaandrade** [comment]
Use `modelsummary` for regression tables

**Comment by luizaandrade** [comment]
> Someone mentioned centering columns~~

merge_cells(1, 4:5) %>% 
  set_align(1, everywhere, "center")
