### ISSUE TITLE
Geospatial data - Feedback April 13 2021

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#71]

**Comment by RRMaximiliano** [comment]
Add information about the @ operator.

**Comment by RRMaximiliano** [comment]
Missing parenthesis in slide 45.

**Comment by RRMaximiliano** [comment]
Just for reference: ST means Spatial Type.

**Comment by RRMaximiliano** [comment]
Some issues with the rgeos packge. Maybe install with dependencies would be needed.

**Comment by luisesanmartin** [comment]
Typo in slide 2: Basuc spatial operations

**Comment by luizaandrade** [comment]
These are all fixed already
