### ISSUE TITLE
R programming practices - Feedback April 14 2021

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#74]

**Comment by RRMaximiliano** [comment]
Part 1 Slide 31.

**Comment by luisesanmartin** [comment]
Changes:

- [ ] Add "Exploring a dataset"
- [ ] Add `purrr`'s map
- [ ] Move loops and apply to the annex

**Comment by luisesanmartin** [comment]
> 
> 
> Part 1 Slide 31.

@RRMaximiliano do you remember what you meant with this? this is the slide:

![image](https://user-images.githubusercontent.com/38444484/139869139-85d6ffa2-d008-44f7-99e0-959d154645b3.png)

**Comment by RRMaximiliano** [comment]
No idea. Maybe it is related to loading packages? The wording seems off as well. @luisesanmartin

**Comment by luisesanmartin** [comment]
must be that. I'll change the instructions.
Thanks
