### ISSUE TITLE
Exploratory Analysis - November 2021

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#83]

**Comment by luisesanmartin** [comment]
Slides 23-24: `skimr` returns an error in live coding when using `N = n` inside the arguments `sfl()` and `skim_with` to generate a summary statistics table.
Perhaps the use of this statistic changed in recent versions of the package?

**Comment by RRMaximiliano** [comment]
Try Obs = length instead of = n.

**Comment by RRMaximiliano** [comment]
> Slides 23-24: `skimr` returns an error in live coding when using `N = n` inside the arguments `sfl()` and `skim_with` to generate a summary statistics table. We don't know why this happens, perhaps the use of this statistic changed in recent versions of the package?

Try Obs = length instead of = n.

**Comment by luisesanmartin** [comment]
An exercise around slides ~25-30 (couldn't see exactly which was it) exports a table with `quick_xlsx()` but doesn't specify the file output path with `here()`. This should be corrected for the exported file to be created in the intended location

**Comment by luizaandrade** [comment]
solved by 9673ac3
