### ISSUE TITLE
May 2022 - Introduction to R

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#92]

**Comment by luisesanmartin** [comment]
it looks like manually importing csv data in RStudio not only loads dataframes into the console but also automatically executes the function `View()`. We need to include an explanation of this in the slides

**Comment by luisesanmartin** [comment]
slide 46 (vector subsetting from dataframes) should go in the dataframes section

**Comment by luisesanmartin** [comment]
the word "dataframe" should be used consistently. There are some slides where we're still using "data set"

**Comment by RRMaximiliano** [comment]
Slide Date: it should be May 2022. I believe I did change that but the repo wasn't pulled.

**Comment by RRMaximiliano** [comment]
Change Slide 13 Screenshot and remove the `rm(list = ls())`

**Comment by RRMaximiliano** [comment]
We gotta check the setting for the learn r app. It seems that after some point we need to keep refreshing the slides.
