### ISSUE TITLE
May 2022 - Descriptive statistics

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-r-training#98]
The prompt of "installing packages from source" is confusing for some participants. We should include something on this in a previous session probably, since it was also mentioned earlier in the course

**Comment by RRMaximiliano** [comment]
- [ ] Mac installation

**Comment by RRMaximiliano** [comment]
install.packages("lfe", dep = TRUE, type = "binary")

**Comment by RRMaximiliano** [comment]
Slides 46. Aggregating observations -- Function (List).

**Comment by luizaandrade** [comment]
`felm` vs `fixest`
